---
- name: Install CTF packages
  community.general.pacman:
    update_cache: true
    name: "{{ item }}"
  with_items:
    - radare2
    - ghidra
    - gdb
    - gef
    - python-keystone
    - python-capstone
    - python-unicorn
